---
abstract: 'Requests throttling for Plack'
author:
  - 'Anton Gerasimov <chim@cpan.org>'
build_requires:
  File::Spec: 0
  File::Temp: 0
  HTTP::Message: 6.01
  IO::Handle: 0
  IPC::Open3: 0
  Plack: 1.0001
  Test::Exception: 0
  Test::More: 0.98
  Test::Pod: 1.22
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Throttle-Lite
no_index:
  directory:
    - t
    - xt
    - eg
    - examples
    - corpus
  namespace:
    - t::lib
  package:
    - DB
provides:
  Plack::Middleware::Throttle::Lite:
    file: lib/Plack/Middleware/Throttle/Lite.pm
    version: 0.05
  Plack::Middleware::Throttle::Lite::Backend::Abstract:
    file: lib/Plack/Middleware/Throttle/Lite/Backend/Abstract.pm
    version: 0.05
  Plack::Middleware::Throttle::Lite::Backend::Simple:
    file: lib/Plack/Middleware/Throttle/Lite/Backend/Simple.pm
    version: 0.05
requires:
  Carp: 1.26
  List::MoreUtils: 0.33
  Net::CIDR::Lite: 0.21
  POSIX: 0
  Plack: 1.0001
  parent: 0
  perl: 5.008009
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/Wu-Wu/Plack-Middleware-Throttle-Lite/issues
  homepage: https://metacpan.org/release/Plack-Middleware-Throttle-Lite
  repository: git://github.com/Wu-Wu/Plack-Middleware-Throttle-Lite.git
version: 0.05
x_authority: cpan:CHIM
